### ISSUE TITLE
getting list of buckets

### ISSUE THREAD

**Issue by jco-c** [influxdata/influxdb-client-r#30]
Hi,

I'd love to be able to get a list of all available buckets in R. This should be possible trough the bucketsAPI of influxdb, right? Are there any plans to implement this into this package?

Thanks alot,
Jan

**Comment by sranka** [comment]
You can send a simple `buckets()` flux script to get a list of buckets in a qury result

**Comment by jco-c** [comment]
Thanks, that worked after setting POSIXxtCol to NULL :) 
I still get a warning though:
`#datatype string long string string string string long`
`The following from values were not present in x: nanotime`
Is there a way to get rid of that?

**Comment by alespour** [comment]
I'm afraid that at the moment you will have to use warning suppression to get rid of that. 

The "issue" here is missing `warn_missing = FALSE` param at https://github.com/influxdata/influxdb-client-r/blob/2752509d8a1ad78c6b3bda385c8c6b33264c9d45/R/influxdb_client.R#L407

And the `"#datatype...` line in output is forgotten `message()` call at https://github.com/influxdata/influxdb-client-r/blob/2752509d8a1ad78c6b3bda385c8c6b33264c9d45/R/influxdb_client.R#L382

**Comment by alespour** [comment]
The above mentioned annoyances are addressed in PR #31

**Comment by alespour** [comment]
Closed via #31
