### ISSUE TITLE
Writing with no time

### ISSUE THREAD

**Issue by thomasbromkapsdata** [influxdata/influxdb-client-r#32]
Hello,
is that possible to write data without setting up time ? (let influxdb put the time of the writing ?)
If no, it can be usefull.
Thanks.

**Comment by alespour** [comment]
No, it's not possible with current version. Honestly, it was never considered an option given how easy is to add column with current time to a data frame in rather rare cases where there are metrics or events without timestamp.

**Comment by thomasbromkapsdata** [comment]
Ok thank you for your fast answer.
It is quite easy to add time yes but more easy to do not do it and a classic feature of influx for me.
It can be convenient to allow influx to write the time when you write from multiple sources/device and you don't want to have time synchronisation problems between them.

**Comment by alespour** [comment]
Fair enough.

**Comment by alespour** [comment]
Can you test current `master`, or you need it published in CRAN?

**Comment by thomasbromkapsdata** [comment]
Tested and approved from the master !
Thank you very much.
