### ISSUE TITLE
Can't write data to influxdb

### ISSUE THREAD

**Issue by troubas** [influxdata/influxdb-client-r#35]
Hei Influxdata

Thank you for providing InfluxDB!
We're playing around with it at the university as part of my studies. I'm trying to write data using the influxdb-client-r.

I'm having some issues writing data to InfluxDB. Everything seems to be going well but there's no data attached to the bucket.
Maybe you can see what I'm doing wrong? Writing data with the python client is working.

```
> client$health()
$name
[1] "influxdb"

$message
[1] "ready for queries and writes"

$status
[1] "pass"

$version
[1] "2.6.1"

$commit
[1] "9dcf880"
```

```
> head(data)
   measurement                                time             x          y           z           a
1 acceleration 2023-03-11T11:12:10.289279488+00:00  1.097191e-02 0.03415753 -0.06364671 -0.06364671
2 acceleration 2023-03-11T11:12:10.300296448+00:00  2.318415e-05 0.05538037 -0.05859122 -0.05859122
3 acceleration 2023-03-11T11:12:10.311343360+00:00 -1.529624e-03 0.05245288 -0.05928239 -0.05928239
4 acceleration 2023-03-11T11:12:10.322391552+00:00 -1.915855e-02 0.05766852 -0.04586967 -0.04586967
5 acceleration 2023-03-11T11:12:10.333395456+00:00 -9.410526e-03 0.06199387 -0.05430975 -0.05430975
6 acceleration 2023-03-11T11:12:10.344455424+00:00 -1.272957e-02 0.07212170 -0.05127688 -0.05127688
```

```
response <- client$write(
    x = data,
    bucket = influxdb$bucket,
    precision = "ns",
    measurementCol = "measurement",
    tagCols = NULL,
    fieldCols = c("a", "x", "y", "z"),
    timeCol = "time",
    object = "lp"
)

> response
NULL
> head(lp[[1]])
[1] "acceleration a=-0.06364671397,x=0.01097190845,y=0.03415752893,z=-0.06364671397 1678533130289"  
[2] "acceleration a=-0.05859122045,x=2.318415073e-05,y=0.05538037273,z=-0.05859122045 1678533130300"
[3] "acceleration a=-0.05928239332,x=-0.001529623763,y=0.05245288198,z=-0.05928239332 1678533130311"
[4] "acceleration a=-0.0458696709,x=-0.01915854827,y=0.05766851612,z=-0.0458696709 1678533130322"   
[5] "acceleration a=-0.05430974754,x=-0.009410526002,y=0.06199386599,z=-0.05430974754 1678533130333"
[6] "acceleration a=-0.05127688358,x=-0.01272957006,y=0.07212170488,z=-0.05127688358 1678533130344"
```

The only curious thing I'm seeing is the following log entries. But I'm honestly not sure what to do with them =/
```
Mar 12 10:41:50 archlinux influxd[289890]: ts=2023-03-12T09:41:50.637618Z lvl=error msg="Unable to write gathered points" log_id=0gWDzxlG000 service=scraper scraper-name="new target" error="database not found: 5826473e9bf79949"
Mar 12 10:42:00 archlinux influxd[289890]: ts=2023-03-12T09:42:00.643621Z lvl=error msg="Unable to write gathered points" log_id=0gWDzxlG000 service=scraper scraper-name="new target" error="database not found: 5826473e9bf79949"
```

**Comment by alespour** [comment]
Hi, the errors in the log are unrelated.

The line protocol output contains timestamp in `ms` precision, no idea why, could be a bug. So the problem is that server is interpreting timestamp values as nanoseconds and that makes it time from the beginning of unix epoch. The workaround could be to set precision to `ms` (and check line output after `write()` protocol again if it matches the precision, you can use eg. https://www.epochconverter.com for validation).

Btw, is `time` column of `nanotime` or `POSIXct` type?

**Comment by troubas** [comment]
I've tried both. Seems like I forgot to adapt the parameter when I created the ticket. The precision in the line protocol matches the parameter of the write function. However in the bucket there's no new entry for the measurement. Which leads to the assumption that the data is never written.

Here we go again:

```
> as_tibble(data)
# A tibble: 3,161 × 6
   measurement  time                                         x      y       z       a
   <chr>        <nanotime>                               <dbl>  <dbl>   <dbl>   <dbl>
 1 acceleration 2023-03-11T11:12:10.289279488+00:00  0.0110    0.0342 -0.0636 -0.0636
 2 acceleration 2023-03-11T11:12:10.300296448+00:00  0.0000232 0.0554 -0.0586 -0.0586
 3 acceleration 2023-03-11T11:12:10.311343360+00:00 -0.00153   0.0525 -0.0593 -0.0593
 4 acceleration 2023-03-11T11:12:10.322391552+00:00 -0.0192    0.0577 -0.0459 -0.0459
 5 acceleration 2023-03-11T11:12:10.333395456+00:00 -0.00941   0.0620 -0.0543 -0.0543
 6 acceleration 2023-03-11T11:12:10.344455424+00:00 -0.0127    0.0721 -0.0513 -0.0513
 7 acceleration 2023-03-11T11:12:10.355487488+00:00 -0.0335    0.0917 -0.0506 -0.0506
 8 acceleration 2023-03-11T11:12:10.366540544+00:00 -0.0244    0.0648 -0.0383 -0.0383
 9 acceleration 2023-03-11T11:12:10.377567488+00:00 -0.0273    0.0749 -0.0353 -0.0353
10 acceleration 2023-03-11T11:12:10.388614400+00:00 -0.0254    0.0972 -0.0203 -0.0203
# … with 3,151 more rows
# ℹ Use `print(n = ...)` to see more rows
> response <- client$write(
+     x = data,
+     bucket = influxdb$bucket,
+     precision = "ns",
+     measurementCol = "measurement",
+     tagCols = NULL,
+     fieldCols = c("a", "x", "y", "z"),
+     timeCol = "time",
+     object = "lp"
+ )
'tagCols' is empty
> head(lp[[1]])
[1] "acceleration a=-0.06364671397,x=0.01097190845,y=0.03415752893,z=-0.06364671397 1678533130289279488"  
[2] "acceleration a=-0.05859122045,x=2.318415073e-05,y=0.05538037273,z=-0.05859122045 1678533130300296448"
[3] "acceleration a=-0.05928239332,x=-0.001529623763,y=0.05245288198,z=-0.05928239332 1678533130311343360"
[4] "acceleration a=-0.0458696709,x=-0.01915854827,y=0.05766851612,z=-0.0458696709 1678533130322391552"   
[5] "acceleration a=-0.05430974754,x=-0.009410526002,y=0.06199386599,z=-0.05430974754 1678533130333395456"
[6] "acceleration a=-0.05127688358,x=-0.01272957006,y=0.07212170488,z=-0.05127688358 1678533130344455424" 
> influxdb$bucket
[1] "bfh-bucket"
```

![image](https://user-images.githubusercontent.com/15320156/224763099-125197e3-9e99-499e-b2c7-adb52a39e3df.png)


As a side note: I've executed `client$write` without starting the server first and didn't get an error in the response. This most likely is a bug?

**Comment by alespour** [comment]
I can see the problem now. The write is not executed. There is `'tagCols' is empty` warning. The client does not allow to write such data.
You can add a column (with string constant as value, if you do not intend to use it) and specify non-NULL `tagCols`.

**Comment by troubas** [comment]
Thanks for the quick response.

I tried it with non-NULL `tagCols` and am seeing the same result.

Seems wierd that the r-client enforces the tag and python-client does not. If I remember the documentation correctly tags are optional for the DB. If that is the case I'd say that's a bug.

Still looks as if write is not executed. The write command still passes without error even though my DB is not running.

**Comment by troubas** [comment]
Maybe the following gist helps you reproduce the issue on your side. I've shortened the data significantly everything else is very close to my local code.
https://gist.github.com/troubas/0680903d26c438954dfc254c8fc38a7d

**Comment by troubas** [comment]
Okay yeah. I found the issue. I quickly started using the 'lp' parameter of the write function not realizing it prevents actual writes to the DB :see_no_evil: 

https://github.com/influxdata/influxdb-client-r/blob/master/R/influxdb_client.R#L241-L245
